Initial try to fix unit test test_value_set_r1_rit().
The problem is, that no spin-id can be generated, since the spins are created manually,

"
File "/sbinlab2/tlinnet/software/NMR-relax/relax_trunk/pipe_control/mol_res_spin.py", line 1498, in generate_spin_id_unique
if res and res.name != None and mol._res_name_count[res.name] > 1:
AttributeError: 'MoleculeContainer' object has no attribute '_res_name_count'
"

Bug #22754 (https://gna.org/bugs/index.php?22754): The minimise.calculate() does not calculate chi2 value for clustered residues.

git-svn-id: svn://svn.gna.org/svn/relax/trunk@26170 b7916896-f9f9-0310-9fe5-b3996d8957d5